### ISSUE TITLE
Enhancement: Mobile responsiveness

### ISSUE THREAD

**Issue by hellodeborahuk** [hellodeborahuk/yoga-site#1]
### Task List

- [ ] hamburger nav
- [x] remove images on class info (and quote?)
- [x] full width text on class info
- [x] margin-bottom on footer
- [x] sort out padding between sections
- [x] blog list page needs doing

![image](https://user-images.githubusercontent.com/29425781/150599552-323ad73b-d656-40cf-a26e-402dccb4af18.png)
