### ISSUE TITLE
Feature: Booking system

### ISSUE THREAD

**Issue by hellodeborahuk** [hellodeborahuk/yoga-site#2]
### Feature

Add a booking system to the website so that students can book classes. An admin panel will need to be created for me to see bookings and set class schedule.

### Task List

- [ ] Plan user story
- [ ] What data does the user need to input
- [ ] Create a mockup of the design
- [ ] Implement the design and backend
