### ISSUE TITLE
Feature: Contact form

### ISSUE THREAD

**Issue by hellodeborahuk** [hellodeborahuk/yoga-site#3]
### Feature

Create a contact form and remove email address from contact.js.

### Task List

- [ ] research if there is there a tool to do this like email.js
- [ ] mock up design
- [ ] add form to page

**Comment by hellodeborahuk** [comment]
Already completed
